"""Create users table

Revision ID: d05a042ab4da
Revises: 09bd5399f592
Create Date: 2025-06-20 13:12:55.239040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05a042ab4da'
down_revision: Union[str, None] = '09bd5399f592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('service_type', sa.Enum('CONSTRUCTION', 'DELIVERY', 'MANUFACTURE', name='tenderservicetype'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PUBLISHED', 'CLOSED', name='tenderstatus'), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_title'), 'tenders', ['title'], unique=False)
    op.create_table('tender_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender_versions')
    op.drop_index(op.f('ix_tenders_title'), table_name='tenders')
    op.drop_table('tenders')
    # ### end Alembic commands ###
